# Generated by Django 4.2.6 on 2023-11-04 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carehomename', models.CharField(max_length=20)),
                ('address_1', models.TextField(max_length=20)),
                ('address_2', models.TextField(blank=True, max_length=20, null=True)),
                ('address_3', models.TextField(blank=True, max_length=20, null=True)),
                ('imageone', models.ImageField(upload_to='care_home_images/')),
                ('type_of_service', models.TextField()),
                ('phone_number', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
