# Generated by Django 4.2.6 on 2023-11-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providerdashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carehome',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
