# Generated by Django 4.2.6 on 2023-11-04 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('providerdashboard', '0002_alter_carehome_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='carehome',
            name='facilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carehome',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
