# Generated by Django 4.2.6 on 2023-11-06 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('providerdashboard', '0003_carehome_facilities_alter_carehome_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('profileimage', models.ImageField(upload_to='person_images/')),
                ('profession', models.CharField(max_length=20)),
                ('add_info', models.TextField()),
                ('payment', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
