# Generated by Django 4.2.6 on 2023-11-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providerdashboard', '0006_timeslot_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_amount',
            field=models.IntegerField(default=0),
        ),
    ]
