# Generated by Django 4.2.6 on 2023-11-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providerdashboard', '0008_timeslot_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carehome',
            name='latitude',
            field=models.DecimalField(decimal_places=30, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='carehome',
            name='longitude',
            field=models.DecimalField(decimal_places=30, max_digits=50, null=True),
        ),
    ]
