# Generated by Django 4.2.6 on 2023-12-20 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('providerdashboard', '0011_carehomereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalPersonReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.CharField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('ProfessionalPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProfessionalPerson_review', to='providerdashboard.professionalperson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofessional_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
