# Generated by Django 4.2.6 on 2023-12-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providerdashboard', '0012_professionalpersonreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='carehomereview',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalpersonreview',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
    ]
