# Generated by Django 4.2.6 on 2023-12-04 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_rename_sender_message_user_remove_message_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='provider_room', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
