# Generated by Django 4.2.6 on 2023-12-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_room_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
